# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import phone.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('marque', models.CharField(max_length=250)),
                ('model_tab', models.CharField(max_length=250)),
                ('prix', models.CharField(max_length=250)),
                ('unite', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to=phone.models.uplaod_location)),
                ('categorie_tablette', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TabletteAccessoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('marque', models.CharField(max_length=250)),
                ('model_tab', models.CharField(max_length=250)),
                ('prix', models.CharField(max_length=250)),
                ('unite', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to=phone.models.uplaod_location)),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('marque', models.CharField(max_length=250)),
                ('model_tel', models.CharField(max_length=250)),
                ('prix', models.CharField(max_length=250)),
                ('unite', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to=phone.models.uplaod_location)),
                ('categorie_telephone', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TelephoneAccessoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('marque', models.CharField(max_length=250)),
                ('model_tel', models.CharField(max_length=250)),
                ('prix', models.CharField(max_length=250)),
                ('unite', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to=phone.models.uplaod_location)),
            ],
        ),
    ]
