# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephone',
            name='desscription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
