# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_telephone_desscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telephone',
            old_name='desscription',
            new_name='description',
        ),
    ]
