# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import electromenager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climatiseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('marque', models.CharField(max_length=250)),
                ('model_climatiseur', models.CharField(max_length=250)),
                ('prix', models.CharField(max_length=250)),
                ('unite', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to=electromenager.models.uplaod_location)),
            ],
        ),
        migrations.CreateModel(
            name='Four',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('marque', models.CharField(max_length=250)),
                ('model_four', models.CharField(max_length=250)),
                ('prix', models.CharField(max_length=250)),
                ('unite', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to=electromenager.models.uplaod_location)),
            ],
        ),
        migrations.CreateModel(
            name='Frigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('marque', models.CharField(max_length=250)),
                ('model_frigo', models.CharField(max_length=250)),
                ('prix', models.CharField(max_length=250)),
                ('unite', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to=electromenager.models.uplaod_location)),
            ],
        ),
        migrations.CreateModel(
            name='Lave_linge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('marque', models.CharField(max_length=250)),
                ('model_lave_linge', models.CharField(max_length=250)),
                ('prix', models.CharField(max_length=250)),
                ('unite', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to=electromenager.models.uplaod_location)),
            ],
        ),
        migrations.CreateModel(
            name='Ventilateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('marque', models.CharField(max_length=250)),
                ('model_ventilateur', models.CharField(max_length=250)),
                ('prix', models.CharField(max_length=250)),
                ('unite', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(upload_to=electromenager.models.uplaod_location)),
            ],
        ),
    ]
